DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS item_in_order;
DROP TABLE IF EXISTS orders_for_user;


CREATE TABLE users(
id INT(11) NOT NULL AUTO_INCREMENT,
first_name VARCHAR (300) NOT NULL DEFAULT "",
last_name VARCHAR (300) NOT NULL DEFAULT "",
email VARCHAR (300) NOT NULL DEFAULT "",
phone VARCHAR (300) NOT NULL DEFAULT "",
address VARCHAR (300) NOT NULL DEFAULT "",
user_name VARCHAR (300) UNIQUE NOT NULL DEFAULT "",
hashed_password VARCHAR (300) NOT NULL DEFAULT "",
PRIMARY KEY (id)
);

CREATE TABLE item(
id INT(11) NOT NULL AUTO_INCREMENT,
item_name VARCHAR (300) UNIQUE NOT NULL DEFAULT "",
price DECIMAL(10,2) NOT NULL,
amount_in_stock INT(11) NOT NULL,
image_url VARCHAR (300),
PRIMARY KEY (id)
);

CREATE TABLE orders(
id INT(11) NOT NULL AUTO_INCREMENT,
buyer_id INT(11) NOT NULL,
order_date DATE NOT NULL,
order_address VARCHAR (300) NOT NULL DEFAULT "",
order_status VARCHAR (300) NOT NULL DEFAULT "",
PRIMARY KEY (id),
FOREIGN KEY (buyer_id) REFERENCES users(id)
);

CREATE TABLE item_in_order(
id INT(11) NOT NULL AUTO_INCREMENT,
order_id INT(11) NOT NULL,
item_id INT(11) NOT NULL,
amount_in_order INT (11) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

